"""add image path into face_recognition

Revision ID: 1685634c4438
Revises: 79e4cab50503
Create Date: 2024-11-18 14:44:17.957733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1685634c4438'
down_revision = '79e4cab50503'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_recognition', sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_recognition', 'image_path')
    # ### end Alembic commands ###
