"""Add particiption_rate column to election table

Revision ID: 1dbf9a78edab
Revises: a8c5b9a16b88
Create Date: 2024-10-14 22:32:11.417641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbf9a78edab'
down_revision = 'a8c5b9a16b88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election', sa.Column('participation_rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('election', 'participation_rate')
    # ### end Alembic commands ###
