"""add face_id into Voter table

Revision ID: 28407856de62
Revises: d7ca2ffb06a0
Create Date: 2024-11-02 23:20:56.956080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28407856de62'
down_revision = 'd7ca2ffb06a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
