"""Add is_approved column to User model

Revision ID: 5c621a7b5439
Revises: 18654e2af152
Create Date: 2024-10-07 21:12:13.470363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c621a7b5439'
down_revision = '18654e2af152'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_approved')
    # ### end Alembic commands ###
