"""add face_id into Voter table

Revision ID: 734cffe2c4e3
Revises: 1dbf9a78edab
Create Date: 2024-11-02 23:13:32.336970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734cffe2c4e3'
down_revision = '1dbf9a78edab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voter', sa.Column('face_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'voter', 'face_recognition', ['face_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voter', type_='foreignkey')
    op.drop_column('voter', 'face_id')
    # ### end Alembic commands ###
