"""remove voter_id onto face_recognition table

Revision ID: 79e4cab50503
Revises: 28407856de62
Create Date: 2024-11-02 23:48:34.151242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e4cab50503'
down_revision = '28407856de62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('face_recognition_voter_id_fkey', 'face_recognition', type_='foreignkey')
    op.drop_column('face_recognition', 'voter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_recognition', sa.Column('voter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('face_recognition_voter_id_fkey', 'face_recognition', 'voter', ['voter_id'], ['id'])
    # ### end Alembic commands ###
