"""Add is_counted column to election table

Revision ID: a8c5b9a16b88
Revises: edc14edea285
Create Date: 2024-10-14 22:06:48.391673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c5b9a16b88'
down_revision = 'edc14edea285'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election', sa.Column('is_counted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('election', 'is_counted')
    # ### end Alembic commands ###
