"""add face_id into Voter table

Revision ID: d7ca2ffb06a0
Revises: 734cffe2c4e3
Create Date: 2024-11-02 23:18:28.412032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ca2ffb06a0'
down_revision = '734cffe2c4e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
